language:
  - python
python:
  - "2.7"
env:
  global:
    - secure: "enzeRwXC4yCzO+qS9Jx1mkFJ3QV8mSVjnRr7E2YXV93z9dMKS3CYriCyVbvXUwpuWbZdrJdKehZgXgD9h7oftTFylREd/UepjhgT33/XpgybXwR6+rPWHBqbGlqSVODMbIW3BJxkCCkDdYEhKKbBO5Ce5YqAxFoFDY1zDzso1fniwGYVEMdigORF1JZzUP6k1HMmxoUV3gtoMGhy6ZFHoubhLpUHGOEcPa9LuY30P691ip+S2MOlLZJy5YdSmJG6G70vC6B9p8uZ2XZJ2uuVzY/zghssSZPN9sGrI5OQvKqWUdWHkQupm/XVXuXwgzVriK/TGqJwxUfi8JkLeJ8u2xtf+/EyTMuT373EnKn8Sq5tp22bPs5p+HFchcon/bWRVNDllvhdfiSx0Tfk1J3fPs464YNWxs4MNgCClh4q5JFDrwxpwQjr3y6BUnbjt/bLLJjifxYFtrQR3akeHFN9QDUu+HeTChrqMzsA109gosPVAsclsVkJTo1VWIG+Y0TGy5Vr0hw+qUHH45pjGW31VGHlQditRPohvtkryzATQZeki0v6SR73ur++1pw/wxQA8KxuNfiXAsZ9Eh+I/WUYSM7C7/1pzbay+0xNAi3GCm12brTFbmd349U0PQ05dX5M+N2wnuQ+qbUaOm1ap96MBtk9e6OmZNwHZPAPSKCaOvo="
script: source .travis.sh
sudo: required

