language:
  - python
python:
  - "2.7"
env:
  global:
    - secure: "TsjW7Di9dHwEQJZs1JFdOfHi+ObBPdxiBStdbyAR6i1Tah8HJk3+xkZXqztmx5mkSjXPQxnkRV0K6KKRQbdI/6Jm+/aUvV315g71J6GNus1FMEvsmxO76Lp26EwAQTDV06MCNYcGEkeAEwx8QSzQoUBzfmp2ZzdsZ+LqDYJdsM2MhBErhnNjLpGJyl8Ju8kd43Y3KkPv5dEk8ItLpvyts53YMNnRLNnZZ6uTKb+o9ndNQwQN8p/KBbmlEg12M3tDJyYvgk8DibdbELKib2KXcJTQpwhn8FTSZSTFhDbrxSElfOV3QcbOEA3L2S3S+ITtU92pjLld/67tb4Vy/UdjrD/C5OfnweDYtKZPtJlvGlzGfphsie/Haid823bv2VHHVWIvU/saaEyZcZObnRwSRz7xsvxZJ0Io19Ph3668lZaGnVDQQhmJjVGOjV+TPCRnrZluaGhLQOwa8EpMMas8wKg5n41zdv4s1Ny9/nB4zMti5np17vKy/FFY+W/mteI9TfSn3PDlCwhr+IumgDJRMd8JGB6CIT7OvT+c3/VHfJO3Wjja4QUJVuF5wCDdj3/z7mm4GKlyiUlat/+1bfIudvHeqsnJmYX8nlkp7dwSH13dtchuX4E0f1SbHsbo1N+kqF00QmhVomKGsHytt85OS70DLCq9ElOiwIeHs7XxGSM="
script: source .travis.sh
sudo: required

